Styles
ewelina-jazurek/coursera-test pull request #16
Opened 2021-05-05 14:46 UTC by ewelina-jazurek

creating files for practice css exercices

2021-05-06 07:23 UTC, grzegorz-jazurek commented on conflicts.html
> +            faucibus cursus. Nunc et vulputate tellus, eu condimentum lectus.</p>
it's better to have opening and closing tags in new lines like:
```
<p>
  lorem ipsum
</p>
```

2021-05-06 07:24 UTC, grzegorz-jazurek commented on floating.html
> +
not needed new line

2021-05-06 07:24 UTC, grzegorz-jazurek commented on floating.html
> +
remove empty line

2021-05-06 07:25 UTC, grzegorz-jazurek commented on font-size.html
> +
not needed empty spaces

2021-05-06 07:26 UTC, grzegorz-jazurek requested changes
please fix formatting and white spaces

2021-05-06 14:06 UTC, ewelina-jazurek commented
corrections made

2021-05-06 19:11 UTC, grzegorz-jazurek commented on CSS-L1.html
> +            <<<<<<< HEAD color: greenyellow;
git conflicts

2021-05-07 15:45 UTC, ewelina-jazurek commented on CSS-L1.html
> +            <<<<<<< HEAD color: greenyellow;
fixed

2021-05-07 15:45 UTC, merged